### ISSUE TITLE
Pre-build binary crashing

### ISSUE THREAD

**Issue by DefenderLab** [fireeye/SilkETW#3]
I am using prebuild binary on windows 7 32 bit and 64 bit Virutal Box images, but it crash on both OS.

**Comment by FuzzySecurity** [comment]
Hey, can you provide any more details about this issue. Do you have steps I can take to reproduce the crash? Please make sure you install the dependencies. I tested the compiled packages on Win7 & Win10 before release.

**Comment by FuzzySecurity** [comment]
I'm closing this issue as I can't reproduce without further details. Please do reopen if you encounter any problems.
