### ISSUE TITLE
SilkService and SilkETW have the same Event Log source causing SilkService to fail

### ISSUE THREAD

**Issue by ion-storm** [fireeye/SilkETW#4]
The sourcename for SilkService "ETW Collector" is the same as SilkETW, if they are both registered, it will prevent silkservice from logging to the eventlog.

**Comment by FuzzySecurity** [comment]
Thank you for the report, I will get a fix for this in the next release :thumbsup:

**Comment by FuzzySecurity** [comment]
This is fixed now in v0.8. At runtime I am checking if "ETW Collector" exists as a source and remove it if it does. I then associate a unique source name with the eventlog log ("SilkETW Collector" or "SilkService Collector").

You don't need to remove the existing log before using the update but you should be aware that until you reboot the source name will incorrectly show "ETW Collector" for new events. This doesn't stop it from working though.
