### ISSUE TITLE
WMI persistance event

### ISSUE THREAD

**Issue by DefenderLab** [fireeye/SilkETW#8]
Which provider should I use to get WMI persistence creation event logs.

**Comment by FuzzySecurity** [comment]
That is something you would have to explore personally. I recommend that you have a look at EtwExplorer:
https://github.com/zodiacon/EtwExplorer

![image](https://user-images.githubusercontent.com/10997340/64021945-f6230300-cb2c-11e9-8419-f2c63602a6d9.png)
